# Generated by Django 3.0.2 on 2020-01-14 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, upload_to='profile_image'),
        ),
    ]
