# Generated by Django 3.0.2 on 2020-01-15 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchit', '0003_auto_20200115_0030'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='contact_no',
            field=models.CharField(default='0', max_length=200),
        ),
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.CharField(default='0', max_length=200),
        ),
    ]
