# Generated by Django 3.0.2 on 2020-01-15 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchit', '0004_auto_20200115_2317'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='contact_no',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='name',
        ),
        migrations.AddField(
            model_name='requesttutor',
            name='contact_no',
            field=models.CharField(default='0', max_length=200),
        ),
        migrations.AddField(
            model_name='requesttutor',
            name='email',
            field=models.CharField(default='0', max_length=200),
        ),
        migrations.AddField(
            model_name='requesttutor',
            name='name',
            field=models.CharField(default='0', max_length=200),
        ),
    ]
