# Generated by Django 3.0.2 on 2020-01-16 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchit', '0005_auto_20200115_2323'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requesttutor',
            name='name',
        ),
        migrations.AddField(
            model_name='profile',
            name='name',
            field=models.CharField(default='0', max_length=200),
        ),
    ]
