# Generated by Django 3.0.2 on 2020-01-16 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchit', '0011_auto_20200116_2311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requesttutor',
            name='contact_no',
            field=models.CharField(default='01234567', max_length=200),
        ),
        migrations.AlterField(
            model_name='requesttutor',
            name='email',
            field=models.CharField(default='johndoe@gmail.com', max_length=200),
        ),
    ]
